import GuideLayout from './GuideLayout';

export default function UnderstandingCreditScores() {
  return (
    <GuideLayout
      title="Understanding Credit Scores"
      subtitle="Decode credit reports, improve your score, and unlock better financial opportunities."
      lastUpdated="October 2025"
    >
      <h2>Introduction</h2>
      <p>
        Your credit score is a three-digit summary of your financial health and reliability, impacting everything from loan approval to credit card offers. Understanding how scores work in India helps you unlock better opportunities.
      </p>

      <h2>Step 1: What Is a Credit Score?</h2>
      <ul>
        <li>In India, scores range from 300 to 900 (higher is better).</li>
        <li>Generated by agencies like CIBIL, Experian, Equifax, and CRIF High Mark.</li>
        <li>Lenders use your score to decide how much and at what rate they’ll lend.</li>
      </ul>

      <h2>Step 2: Key Factors Influencing Your Score</h2>
      <ul>
        <li>
          <strong>Payment History (35%):</strong> Timely repayments of loans/credit cards have the biggest impact.
        </li>
        <li>
          <strong>Credit Utilization (30%):</strong> Percentage of available credit you use—keep it below 30% for best results.
        </li>
        <li>
          <strong>Length of Credit History (15%):</strong> Older accounts show stability. Don’t close old cards unless necessary.
        </li>
        <li>
          <strong>Credit Mix (10%):</strong> A mix of secured (home/car loan) and unsecured (cards/personal loan) credit is better than just one type.
        </li>
        <li>
          <strong>New Credit (10%):</strong> Too many new loan/card applications temporarily lower your score.
        </li>
      </ul>

      <h2>Step 3: How to Check Your Credit Score</h2>
      <ol>
        <li>Visit official agency sites: <a href="https://www.cibil.com">CIBIL</a>, Experian, Equifax, or CRIF High Mark.</li>
        <li>Enter PAN and details—one free check per year is mandated.</li>
        <li>Review your credit report—check for errors or fraudulent entries!</li>
      </ol>

      <h2>Step 4: Steps to Improve Your Score</h2>
      <ul>
        <li>Always pay bills/EMIs on time—activate autopay or reminders.</li>
        <li>Reduce credit card balances; keep utilization below 30% of your limit.</li>
        <li>Avoid applying for multiple new loans/cards within a short span.</li>
        <li>Don’t close old, well-managed credit cards.</li>
        <li>Diversify—if possible, mix secured and unsecured credit (e.g., fixed deposit-backed credit card).</li>
        <li>Dispute errors—report any mistakes or fraud to the bureau immediately for correction.</li>
      </ul>
      <div style={{
        background: '#F3E5F5',
        borderLeft: '6px solid #8E24AA',
        padding: '16px',
        margin: '16px 0',
      }}>
        <strong>Tip:</strong> If CIBIL/Experian shows “No Record” (new borrowers), get a secured card or add a small loan to start your history.
      </div>

      <h2>Regional Nuances & Advice</h2>
      <ul>
        <li>Many Indian lenders also view behavioral patterns—salary inflow, spending, and digital activity can matter for fintech approvals.</li>
        <li>Even informal borrowings (chit funds, local co-ops) don’t count toward your formal credit score, but digital lending apps may begin reporting soon.</li>
      </ul>

      <h2>Resources & Apps</h2>
      <ul>
        <li>
          <strong>Score Checkers:</strong> Walnut, Bank apps (HDFC, ICICI, SBI), CRED, Paisabazaar
        </li>
        <li>
          <strong>Repair Help:</strong> “Credit Score Repair” step-by-step guides (online blogs, YouTube)
        </li>
        <li>
          <strong>Further Reading:</strong> “Let’s Talk Money” by Monika Halan; RBI site for latest lending rules
        </li>
      </ul>

      <h2>Frequently Asked Questions</h2>
      <ul>
        <li><strong>Can I improve my score quickly?</strong><br /> Small improvements show up in months; larger issues may take a year or more. Consistency is key.</li>
        <li><strong>Will checking my score often hurt it?</strong><br /> No—self-inquiries do not affect your score. Only official lender checks do.</li>
        <li><strong>Why is my score low even without loans?</strong><br /> Lack of history or late credit card payments; start with a small credit product and pay consistently.</li>
      </ul>

      <h2>Conclusion</h2>
      <p>
        Your credit score is changeable! Understand the factors, act consistently, and use your score to access better financial opportunities. Check yearly, fix errors, and stay disciplined.
      </p>
    </GuideLayout>
  );
}
